stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:13
  script:
    - npm install
    - npm run test

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/simonbreiter/color-name .
    - docker push $DOCKER_REGISTRY/simonbreiter/color-name

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${K8S_API_URL}"
    - kubectl config set clusters.k8s.certificate-authority-data ${K8S_CA_CERTIFICATE}
    - kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -k ./k8s
