stages:
  - test
  - build

test:
  image: node:7
  script:
    - npm install
    - npm run test

build:
  image: docker:latest
  services:
  - docker:dind
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/simonbreiter/color-name .
    - docker push $DOCKER_REGISTRY/simonbreiter/color-name
