stages:
  - build
  - test
  - docker
  - deploy

build:
  stage: build
  image: node:13
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - node_modules
  script:
    - npm install
    - npm run build

test:
  stage: test
  image: node:13
  script:
    - npm run test

docker:
  stage: docker
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/simonbreiter/color-name .
    - docker push $DOCKER_REGISTRY/simonbreiter/color-name

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${K8S_API_URL}"
    - kubectl config set clusters.k8s.certificate-authority-data $(echo ${K8S_CA_CERTIFICATE} | base64 -i -)
    - kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -k ./k8s
